In [17]:
# simple  addition
x=1
for i in range (5): 
    y=x+2
    x += 1
    print(x, "= is the base value //", y, "= is the results")



2 = is the base value // 3 = is the results
3 = is the base value // 4 = is the results
4 = is the base value // 5 = is the results
5 = is the base value // 6 = is the results
6 = is the base value // 7 = is the results


In [20]:
# Array calculations
import numpy as np
L1 =  np.array([1.,4.,3.])
L2 =  np.array([1.,2.,3.])

print(L1)
print(L2)
print("+", L1+L2)
print("-",L1-L2)
print("*",L1*L2)
print("/",L1/L2)
print("**",L1**L2)

[1. 4. 3.]
[1. 2. 3.]
+ [2. 6. 6.]
- [0. 2. 0.]
* [1. 8. 9.]
/ [1. 2. 1.]
** [ 1. 16. 27.]


In [21]:
import numpy as np
print(np.arange(5))



[0 1 2 3 4]
